modLoader="javafml"
loaderVersion="[25,)"
issueTrackerURL="https://github.com/Vazkii/AutoRegLib"

[[mods]]
modId="autoreglib"
displayName="AutoRegLib"
version="${version}"
authors="Vazkii"
description='''
Automatically item, block, and model registration for mods.
'''
